function [Delta_approx, Del_Gam_approx,FullValue_approx ] = American_Approximations(S0,St,K1,K3,mp,mc1,mc2,T,tau,r,Sigma,NumOfTimeSteps,alpha,lambda,M)

put=priceOptionTrinCEVAmericanTry1(S0, K1, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, 'Put');
Call_1=priceOptionTrinCEVAmericanTry1(S0, K1, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, 'Call');
           
Call_2=priceOptionTrinCEVAmericanTry1(S0, K3, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, 'Call');           
           



Del_prfl    = mp*(Interp_AuxLatticeGreeksAmerican(S0, K1, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, 'Put', 'delta')) +  mc1*(Interp_AuxLatticeGreeksAmerican(S0, K1, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, 'Call', 'delta'))...  
                    + mc2* (Interp_AuxLatticeGreeksAmerican(S0, K3, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, 'Call', 'delta'));
                
Gam_prfl    = mp*(Interp_AuxLatticeGreeksAmerican(S0, K1, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, 'Put', 'gamma')) +  mc1*(Interp_AuxLatticeGreeksAmerican(S0, K1, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, 'Call','gamma'))...  
                    + mc2* (Interp_AuxLatticeGreeksAmerican(S0, K3, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M,  'Call','gamma'));
                 

American_Call_1=priceOptionTrinCEVAmericanTry1(St, K1, r, T-tau, ...
                NumOfTimeSteps,  Sigma,alpha,lambda,M, 'Call');
American_Put=priceOptionTrinCEVAmericanTry1(St, K1, r, T-tau, ...
                NumOfTimeSteps,  Sigma,alpha,lambda,M, 'Put');
American_Call_2 =priceOptionTrinCEVAmericanTry1(St, K3, r, T-tau, ...
                NumOfTimeSteps,  Sigma,alpha,lambda,M, 'Call');
%%%% portfolio value today
P0 = mp*put + mc1*Call_1 + mc2*Call_2 ;

%Delta approximation
Delta_approx = P0 + Del_prfl * (St - S0) ;

% Delta_Gamma approximation
Del_Gam_approx = P0 + Del_prfl *(St-S0) + 0.5*Gam_prfl*(St - S0)^2;

%%% full valuation
FullValue_approx = mp*American_Put + mc1*American_Call_1  +  mc2*American_Call_2 ;


