function [ gammaG ] = TrinGammaAsianGp(Underlying, Strike, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)
          S  = Underlying;

dS=S.*(Sigma.*S.^(alpha/2-1).*sqrt(T));

gammaG=((priceOptionTrinCEVAsianGTry1(S+dS, Strike, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)-...
                2.*priceOptionTrinCEVAsianGTry1(S, Strike, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)...
              + priceOptionTrinCEVAsianGTry1(S-dS, Strike, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut))./(dS^2));

end