function [ gamma ] = TrinGammaEuropeanp(Underlying, Strike, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)
          S  = Underlying;

dS=S.*(Sigma.*S.^(alpha/2-1).*sqrt(T));

gamma=((priceOptionTrinCEVEuropeanTry1(S+dS, Strike, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)-...
                2.*priceOptionTrinCEVEuropeanTry1(S, Strike, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)...
              + priceOptionTrinCEVEuropeanTry1(S-dS, Strike, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut))./(dS^2));

end