function [ gamma ] = TrinGammaAmericanp(Underlying, Strike, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)
          S  = Underlying;

dS=S.*(Sigma.*S.^(alpha/2-1).*sqrt(T));

gamma=((priceOptionTrinCEVAmericanTry1(S+dS, Strike, r, T, ...
                NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)-...
                2.*priceOptionTrinCEVAmericanTry1(S, Strike, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut)...
              + priceOptionTrinCEVAmericanTry1(S-dS, Strike, r, T, ...
               NumOfTimeSteps, Sigma,alpha,lambda,M, StrCallPut))./(dS^2));

end